from bs4 import Tag

from scrapers.base import BaseScraper
from scrapers.model import Discount

_DISCOUNT_CODE_CLASS = "css-o15es7 e19v4qza1"
_DISCOUNT_ITEM_CLASS = "dnb-anchor--no-style dnb-anchor--no-hover dnb-anchor--no-underline etl9f1w0 css-19gq7c4 e1ig56cy0 dnb-anchor dnb-anchor--was-node dnb-a"
_STORE_HEADING_CLASS = "dnb-heading dnb-h--medium css-5pbyeb etl9f1w4"
_DISCOUNT_AMOUNT_CLASS = "css-atp9e0 etl9f1w6"
# Note: the hash-like tokens above (e.g. css-o15es7, etl9f1w0) are auto-generated by
# DNB's CSS-in-JS framework and may change when the site is redeployed.

class DnbScraper(BaseScraper):
    site_name = "DNB"
    base_url = "https://www.dnb.no"
    list_url = "https://www.dnb.no/kundeprogram/fordeler/faste-rabatter"


    def scrape(self) -> list[Discount]:
        soup = self.fetch(self.list_url)

        discount_code_element = soup.find("span", class_=_DISCOUNT_CODE_CLASS)
        if not discount_code_element:
            raise ValueError(f"{self.site_name}: Could not find discount code element. The page structure may have changed.")
        static_discount_code = discount_code_element.get_text(strip=True)

        items = soup.find_all("a", class_=_DISCOUNT_ITEM_CLASS)
        if not items:
            raise ValueError(f"{self.site_name}: Could not find any discount items. The page structure may have changed.")

        return [self.scrape_item(item, static_discount_code) for item in items]

    def scrape_item(self, item: Tag, discount_code: str) -> Discount:
        store = item.find("h3", class_=_STORE_HEADING_CLASS).get_text(strip=True)
        discount = item.find("span", class_=_DISCOUNT_AMOUNT_CLASS).get_text(strip=True)
        description = discount + " by using code " + discount_code
        full_link = item.get("href")
        return Discount(
            store=store,
            description=description,
            discount=discount,
            code=discount_code,
            expires_at=None,
            link=full_link,
        )
